version: "3"
services:
  api:
    image: node:18-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
     - ./.env
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${TYPEORM_PASSWORD}"
      MYSQL_DATABASE: "${TYPEORM_DATABASE}"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/log/rabbitmq/data
        - ~/.docker-conf/rabbitmq/log/:/log/rabbitmq/log