version: "3"
services:
  api:
    image: node:18-alpine
    command: sh -c "npm install && npm run start:dev && npm run typeorm:migration:run"
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
      - rabbitmq
    env_file:
     - ./.env
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - db:${TYPEORM_HOST}
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${TYPEORM_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/log/rabbitmq/data
        - ~/.docker-conf/rabbitmq/log/:/log/rabbitmq/log
volumes:
  db-data: