version: "3"
services:
  api:
    image: node:18-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: maintenance_tasks
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080